---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

helmCharts:
- name: external-dns
  releaseName: external-dns
  namespace:  external-dns
  version: 1.11.0
  repo: https://kubernetes-sigs.github.io/external-dns/
  valuesFile: values.cue.yaml
