---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

helmCharts:
- name: ingress-nginx
  releaseName: ingress-nginx
  namespace:  ingress-nginx
  version: 4.3.0
  repo: https://kubernetes.github.io/ingress-nginx
  valuesFile: values.cue.yaml
