---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace:  cert-manager
  version: 1.10.0
  repo: https://charts.jetstack.io
  valuesFile: values.cue.yaml
