---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
- name: prometheus-node-exporter
  releaseName: prometheus-node-exporter
  namespace:  monitoring
  version: 4.5.0
  repo: https://prometheus-community.github.io/helm-charts
  valuesFile: values.cue.yaml
