---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
- name: victoria-metrics-single
  releaseName: victoria-metrics
  namespace:  monitoring
  version: 0.8.41
  repo: https://victoriametrics.github.io/helm-charts/
  valuesFile: values.cue.yaml
